spring.application.name=tutormatch
server.port=8081

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=tutormatch123

jwt.secret=tutormatchUVGsecretkey2024verylongkeyforHMACsha256algorithmrequires256bits
jwt.expiration=86400000
